# Generated by Django 6.0.4 on 2026-04-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_ops', '0001_initial'),
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_ros', to='admin_ops.systemuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ro_profile', to='admin_ops.systemuser')),
            ],
            options={
                'db_table': 'registration_officers',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('activation_challenge', models.CharField(blank=True, max_length=64, null=True)),
                ('activation_challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_request', to='citizens.citizen')),
                ('ro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrollments', to='admin_ops.systemuser')),
            ],
            options={
                'db_table': 'enrollment_requests',
                'indexes': [models.Index(fields=['status'], name='enrollment__status_cec149_idx'), models.Index(fields=['submitted_at'], name='enrollment__submitt_daa962_idx')],
            },
        ),
    ]
