# Generated by Django 6.0.4 on 2026-04-25 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0003_alter_systemuser_password_hash_and_more'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='ro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests_reviewed', to='admin_ops.systemuser'),
        ),
    ]
