from pydantic import BaseModel, Field, ConfigDict
from pydantic.networks import IPvAnyAddress
from datetime import datetime
from enum import Enum
from typing import Optional, Any

# -------------------------------------------------------------------
# Enums
# -------------------------------------------------------------------
class Outcome(str, Enum):
    SUCCESS = 'SUCCESS'
    FAILURE = 'FAILURE'


# -------------------------------------------------------------------
# Shared Base Schema
# -------------------------------------------------------------------
class AuditLogBase(BaseModel):
    actor_id: str = Field(..., max_length=50, description="ID (DIN or System ID) of the actor")
    actor_role: str = Field(..., max_length=30, description="Role of the actor (e.g., RO, ADMIN, SYSTEM)")
    action: str = Field(..., max_length=100, description="Action performed (e.g., ENROLL_CITIZEN, APPROVE_KYC)")
    target_type: str = Field(..., max_length=50, description="Entity type affected (e.g., CITIZEN, BIOMETRIC)")
    target_id: str = Field(..., max_length=50, description="Unique ID/DIN of the affected entity")
    outcome: Outcome = Field(default=Outcome.SUCCESS)
    ip_address: Optional[IPvAnyAddress] = Field(None, description="IP Address from which the request originated")
    metastamp: Optional[dict[str, Any]] = Field(None, description="Additional context or metadata (JSON)")


# -------------------------------------------------------------------
# Create Schema
# -------------------------------------------------------------------
class AuditLogCreate(AuditLogBase):
    """
    POST /audit-logs/ (Internal Use)
    Used by internal microservices or middleware to log an event.
    Timestamp is automatically generated by the database.
    """
    log_signature: Optional[str] = Field(None, max_length=64, description="Cryptographic signature of the log payload")


# -------------------------------------------------------------------
# Response Schema
# -------------------------------------------------------------------
class AuditLogResponse(AuditLogBase):
    """
    GET /audit-logs/{id}
    Standard response for an individual audit log entry.
    """
    model_config = ConfigDict(from_attributes=True)

    id: int
    timestamp: datetime
    log_signature: Optional[str] = Field(None, max_length=64)


# -------------------------------------------------------------------
# List & Pagination Schemas
# -------------------------------------------------------------------
class PaginatedAuditLogList(BaseModel):
    """
    GET /audit-logs/?page=1&size=50
    Paginated list for Admin/Security dashboards.
    """
    total: int
    page: int
    page_size: int
    items: list[AuditLogResponse]


# -------------------------------------------------------------------
# Query Filters
# -------------------------------------------------------------------
class AuditLogFilterParams(BaseModel):
    """
    Query parameters for GET /audit-logs/
    Highly useful for security auditing and searching.
    """
    actor_id: Optional[str] = None
    action: Optional[str] = None
    target_type: Optional[str] = None
    target_id: Optional[str] = None
    outcome: Optional[Outcome] = None
    
    # Date range filters are essential for audit logs
    start_time: Optional[datetime] = Field(None, description="Filter logs starting from this timestamp")
    end_time: Optional[datetime] = Field(None, description="Filter logs up to this timestamp")
    
    page: int = Field(default=1, ge=1)
    page_size: int = Field(default=50, ge=1, le=100)