# Generated by Django 6.0.4 on 2026-04-29 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citizens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BurialPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorised_by_name",
                    models.CharField(
                        help_text="Name of person/entity authorised to carry out the burial",
                        max_length=255,
                    ),
                ),
                (
                    "deceased_name",
                    models.CharField(
                        help_text="Full name of the deceased", max_length=255
                    ),
                ),
                (
                    "place_of_death",
                    models.CharField(
                        help_text="Where the deceased died", max_length=255
                    ),
                ),
                ("date_of_death", models.DateField()),
                (
                    "issuing_authority",
                    models.CharField(
                        choices=[
                            ("REGISTRAR", "Registrar"),
                            ("MAGISTRATE", "Magistrate"),
                            ("POLICE", "Police Officer"),
                            ("OTHER", "Other Officer Specially Empowered"),
                        ],
                        help_text="Which authority signed this permit",
                        max_length=20,
                    ),
                ),
                (
                    "issuing_officer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "issuing_officer_signature",
                    models.TextField(
                        blank=True,
                        help_text="Base64 signature or file reference",
                        null=True,
                    ),
                ),
                ("issued_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "burial_permit",
            },
        ),
        migrations.CreateModel(
            name="MedicalCertificateCauseOfDeath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medical_no",
                    models.CharField(
                        help_text="Pre-printed medical number on the counterfoil",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "attended_name",
                    models.CharField(
                        help_text="Full name of the person the doctor attended",
                        max_length=255,
                    ),
                ),
                (
                    "illness_start_date",
                    models.DateField(
                        help_text="Date doctor first attended during last illness"
                    ),
                ),
                (
                    "last_attended_alive_date",
                    models.DateField(
                        help_text="Date doctor last attended the deceased alive"
                    ),
                ),
                (
                    "last_attended_alive_day",
                    models.PositiveSmallIntegerField(
                        help_text="Day of month — last attended alive (mirrors paper form layout)"
                    ),
                ),
                ("death_date", models.DateField(help_text="Date the person died")),
                (
                    "death_day",
                    models.PositiveSmallIntegerField(
                        help_text="Day of month — died (mirrors paper form layout)"
                    ),
                ),
                (
                    "death_year",
                    models.PositiveSmallIntegerField(
                        help_text="Year — died (last 2 digits as on form)"
                    ),
                ),
                (
                    "death_time",
                    models.TimeField(
                        blank=True, help_text="Time of death if recorded", null=True
                    ),
                ),
                (
                    "body_identified_of",
                    models.CharField(
                        help_text="Name of person whose body was formally identified",
                        max_length=255,
                    ),
                ),
                (
                    "age_stated",
                    models.CharField(
                        help_text="Age as stated on the form e.g. '45 years'",
                        max_length=20,
                    ),
                ),
                (
                    "postmortem_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether cause of death was confirmed by post-mortem examination",
                    ),
                ),
                (
                    "cause_a",
                    models.CharField(
                        help_text="(a) Disease or condition directly leading to death",
                        max_length=255,
                    ),
                ),
                (
                    "cause_a_interval",
                    models.CharField(
                        blank=True,
                        help_text="Approximate interval between onset and death for (a)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "cause_a_icd_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cause_b",
                    models.CharField(
                        blank=True,
                        help_text="(b) Morbid condition giving rise to (a) — accidental cause",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "cause_b_interval",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cause_b_icd_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "cause_c",
                    models.CharField(
                        blank=True,
                        help_text="(c) Underlying condition giving rise to (b)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "cause_c_interval",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cause_c_icd_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "other_condition_1",
                    models.CharField(
                        blank=True,
                        help_text="Section II — other significant condition 1",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "other_condition_1_interval",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "other_condition_2",
                    models.CharField(
                        blank=True,
                        help_text="Section II — other significant condition 2",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "other_condition_2_interval",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "witness_date",
                    models.DateField(
                        help_text="Date the doctor signed the certificate"
                    ),
                ),
                (
                    "certificate_handed_to",
                    models.CharField(
                        help_text="Name and address of person to whom certificate was handed",
                        max_length=255,
                    ),
                ),
                ("medical_attendant_name", models.CharField(max_length=255)),
                (
                    "medical_attendant_signature",
                    models.TextField(
                        blank=True,
                        help_text="Base64 signature or file reference",
                        null=True,
                    ),
                ),
                ("medical_attendant_qualification", models.CharField(max_length=255)),
                ("medical_attendant_residence", models.CharField(max_length=255)),
                ("village", models.CharField(blank=True, max_length=100, null=True)),
                ("chief", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("informant_name", models.CharField(max_length=255)),
                (
                    "informant_relationship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "informant_contact_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("informant_postal_address", models.TextField(blank=True, null=True)),
                ("informant_signature", models.TextField(blank=True, null=True)),
                ("informant_declaration_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Medical Certificate of Cause of Death",
                "db_table": "mccd",
            },
        ),
        migrations.CreateModel(
            name="NoticeOfBirth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Pre-printed serial on the form e.g. 0050984",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                (
                    "date_and_time",
                    models.DateTimeField(
                        help_text="Official date and time recorded by facility"
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "place_of_birth",
                    models.CharField(
                        choices=[
                            ("HEALTH_FACILITY", "Health Facility"),
                            ("HOME", "Home"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "health_facility_name",
                    models.CharField(
                        blank=True,
                        help_text="Required if born at health facility",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "home_address",
                    models.TextField(
                        blank=True, help_text="Required if born at home", null=True
                    ),
                ),
                (
                    "other_place_specified",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("child_surname", models.CharField(max_length=100)),
                ("child_given_name", models.CharField(max_length=100)),
                (
                    "child_other_names",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "birth_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Birth weight in kilograms",
                        max_digits=4,
                    ),
                ),
                (
                    "father_surname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_other_names",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("father_dob", models.DateField(blank=True, null=True)),
                (
                    "father_national_id",
                    models.CharField(
                        blank=True,
                        help_text="NRC / National Identity No.",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_social_id",
                    models.CharField(
                        blank=True,
                        help_text="Social Identity / NAPSA No.",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "father_village_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_chief",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_tribe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "father_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_residential_address", models.TextField(blank=True, null=True)),
                (
                    "father_contact_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("mother_surname", models.CharField(max_length=100)),
                (
                    "mother_other_names",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mother_maiden_surname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mother_dob", models.DateField(blank=True, null=True)),
                (
                    "mother_national_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "mother_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_social_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "mother_village_of_origin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_chief",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_tribe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mother_education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "Never Been to School"),
                            ("PRIMARY", "Primary"),
                            ("SECONDARY", "Secondary"),
                            ("TERTIARY", "Tertiary"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("mother_residential_address", models.TextField(blank=True, null=True)),
                (
                    "mother_usual_place_of_residence",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "attendant_at_birth",
                    models.CharField(
                        choices=[
                            ("MIDWIFE", "Qualified Midwife"),
                            ("TBA", "Traditional Birth Attendant"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "attendant_other_specified",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("MARRIED", "Married"),
                            ("NOT_MARRIED", "Not Married"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "father_acknowledgement_signature",
                    models.TextField(
                        blank=True,
                        help_text="Base64 signature — father acknowledges paternity",
                        null=True,
                    ),
                ),
                (
                    "father_acknowledgement_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "mother_consent_signature",
                    models.TextField(
                        blank=True,
                        help_text="Base64 signature — mother consents to father being registered",
                        null=True,
                    ),
                ),
                ("mother_consent_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notice_of_birth",
            },
        ),
        migrations.CreateModel(
            name="NoticeOfDeath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=20, unique=True)),
                (
                    "application_no",
                    models.CharField(
                        blank=True,
                        help_text="Shaded field — assigned by official on receipt",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "date_and_time",
                    models.DateTimeField(
                        help_text="Official date and time recorded on the form"
                    ),
                ),
                (
                    "deceased_din",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("surname", models.CharField(max_length=100)),
                (
                    "other_names",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("residential_address", models.TextField(blank=True, null=True)),
                ("district", models.CharField(max_length=100)),
                ("date_of_death", models.DateField()),
                (
                    "place_of_death",
                    models.CharField(
                        choices=[
                            ("HEALTH_FACILITY", "Health Facility"),
                            ("HOME", "Home"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "place_of_death_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of health facility or description of home/other location",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "place_of_death_other",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "age_at_death",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "national_identity_no",
                    models.CharField(
                        blank=True, help_text="NRC number", max_length=30, null=True
                    ),
                ),
                (
                    "social_security_no",
                    models.CharField(
                        blank=True, help_text="NAPSA number", max_length=30, null=True
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "Never Been to School"),
                            ("PRIMARY", "Primary"),
                            ("SECONDARY", "Secondary"),
                            ("TERTIARY", "Tertiary"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "death_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NATURAL", "Natural Death"),
                            ("SUDDEN", "Sudden Death — Post Mortem Required"),
                            ("UNNATURAL", "Unnatural Cause"),
                        ],
                        help_text="Health Facility / Home Based / Brought In Dead / Unnatural",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "immediate_cause",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "immediate_cause_icd",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "antecedent_cause",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "antecedent_cause_icd",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "underlying_cause",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "underlying_cause_icd",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "police_certifier_name",
                    models.CharField(
                        blank=True,
                        help_text="MR/MRS/MS name of certifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "police_certifier_residence",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "police_certifier_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to deceased — confirms bringing in body",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "deceased_surname_police",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "deceased_other_names_police",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "deceased_age_police",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("passed_away_date", models.DateField(blank=True, null=True)),
                ("passed_away_time", models.TimeField(blank=True, null=True)),
                (
                    "passed_away_place",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("suddenly_suffering_from", models.TextField(blank=True, null=True)),
                (
                    "treatment_was_at",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_natural_death", models.BooleanField(blank=True, null=True)),
                (
                    "is_sudden_death_postmortem_required",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "police_no_and_rank",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "police_formation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "police_officer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "police_officer_signed",
                    models.TextField(
                        blank=True,
                        help_text="Base64 signature or file reference",
                        null=True,
                    ),
                ),
                ("police_officer_date", models.DateField(blank=True, null=True)),
                ("doctors_remarks", models.TextField(blank=True, null=True)),
                (
                    "pupils_dilated_and_fixed",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "certifying_doctor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "certifying_doctor_signature",
                    models.TextField(blank=True, null=True),
                ),
                ("certifying_doctor_date", models.DateField(blank=True, null=True)),
                ("informant_surname", models.CharField(max_length=100)),
                (
                    "informant_other_names",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "informant_relationship",
                    models.CharField(
                        help_text="Relationship to the deceased", max_length=100
                    ),
                ),
                (
                    "informant_contact_no",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "informant_national_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "informant_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "informant_residential_address",
                    models.TextField(blank=True, null=True),
                ),
                ("informant_postal_address", models.TextField(blank=True, null=True)),
                ("date_of_registration", models.DateField(blank=True, null=True)),
                (
                    "has_mccd",
                    models.BooleanField(
                        default=False, help_text="Original MCCD attached"
                    ),
                ),
                (
                    "has_informant_national_id",
                    models.BooleanField(
                        default=False, help_text="Copy of informant's NID attached"
                    ),
                ),
                (
                    "has_coroner_report",
                    models.BooleanField(
                        default=False,
                        help_text="Coroner's report attached (unnatural death)",
                    ),
                ),
                (
                    "informant_declaration_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "informant_declaration_signature",
                    models.TextField(blank=True, null=True),
                ),
                ("informant_declaration_date", models.DateField(blank=True, null=True)),
                (
                    "assistant_registrar_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "assistant_registrar_signature",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "registrar_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("registrar_signature", models.TextField(blank=True, null=True)),
                (
                    "official_stamp_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notice_of_death",
            },
        ),
        migrations.CreateModel(
            name="RecordOfBirth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=20, unique=True)),
                (
                    "file_number",
                    models.CharField(
                        blank=True,
                        help_text="Facility file / case number",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("place_of_birth", models.CharField(max_length=255)),
                ("child_surname", models.CharField(max_length=100)),
                (
                    "child_other_names",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "birth_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="BWT — birth weight in kilograms",
                        max_digits=4,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("time_of_birth", models.TimeField()),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_present_address", models.TextField(blank=True, null=True)),
                ("mother_name", models.CharField(max_length=255)),
                (
                    "officer_in_charge",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "official_stamp_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reference or scan path for the official stamp",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("date_signed", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "record_of_birth",
            },
        ),
        migrations.CreateModel(
            name="BirthCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_no", models.CharField(max_length=20, unique=True)),
                ("district", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("place_of_birth", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=100)),
                (
                    "other_names",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "father_occupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_nssf", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "father_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("father_nid", models.CharField(blank=True, max_length=30, null=True)),
                ("mother_name", models.CharField(max_length=255)),
                (
                    "mother_maiden",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mother_nssf", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "mother_nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("mother_nid", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "informant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("informant_address", models.TextField(blank=True, null=True)),
                (
                    "postal_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_of_registration", models.DateField()),
                ("registrar_name", models.CharField(max_length=255)),
                ("certificate_url", models.URLField(blank=True, null=True)),
                (
                    "verification_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "father_system_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birth_certificates_as_father",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mother_system_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birth_certificates_as_mother",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "birth_certificate",
            },
        ),
        migrations.CreateModel(
            name="DeathCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_no",
                    models.CharField(
                        help_text="Official registration number assigned by Registrar",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("date_of_death", models.DateField()),
                ("district", models.CharField(max_length=100)),
                ("place_of_death", models.CharField(max_length=255)),
                ("deceased_names_and_surname", models.CharField(max_length=255)),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                (
                    "age",
                    models.CharField(
                        help_text="Age as recorded e.g. '62 years'", max_length=20
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "napsa_social_security_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "national_identity_no",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "cause_of_death",
                    models.TextField(
                        help_text="Full cause of death as certified — may be multi-line (a/b/c)"
                    ),
                ),
                ("informant_name", models.CharField(max_length=255)),
                ("informant_relationship", models.CharField(max_length=100)),
                ("date_of_registration", models.DateField()),
                (
                    "register_kept_at",
                    models.CharField(
                        help_text="Location of the register e.g. 'Lusaka District Registry'",
                        max_length=255,
                    ),
                ),
                ("issued_date", models.DateField()),
                (
                    "registrar_general_name",
                    models.CharField(
                        help_text="Name of the Registrar-General / Deputy / Registrar who signed",
                        max_length=255,
                    ),
                ),
                (
                    "registrar_general_signature",
                    models.TextField(
                        blank=True,
                        help_text="Base64 signature or file reference",
                        null=True,
                    ),
                ),
                (
                    "official_stamp_ref",
                    models.CharField(
                        blank=True,
                        help_text="Embossed official seal reference",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mccd",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="death_certificate",
                        to="hospital.medicalcertificatecauseofdeath",
                    ),
                ),
                (
                    "notice_of_death",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="death_certificate",
                        to="hospital.noticeofdeath",
                    ),
                ),
            ],
            options={
                "db_table": "death_certificate",
            },
        ),
        migrations.CreateModel(
            name="DeathRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("ready_for_review", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "burial_permit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burial_permit",
                        to="hospital.burialpermit",
                    ),
                ),
                (
                    "death_certificate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="death_record",
                        to="hospital.deathcertificate",
                    ),
                ),
                (
                    "health_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_worker_that_submitted_inital_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "informant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="informant_that_submits_death_notice",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="death_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="death_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "medical_certificate_of_death",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mccd",
                        to="hospital.medicalcertificatecauseofdeath",
                    ),
                ),
                (
                    "notice_of_death",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_of_death",
                        to="hospital.noticeofdeath",
                    ),
                ),
            ],
            options={
                "db_table": "death_registration_request",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddField(
            model_name="burialpermit",
            name="notice_of_death",
            field=models.OneToOneField(
                blank=True,
                help_text="The Notice of Death this permit was issued against",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="burial_permit",
                to="hospital.noticeofdeath",
            ),
        ),
        migrations.CreateModel(
            name="OfflineSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[("BIRTH", "Birth"), ("DEATH", "Death")], max_length=10
                    ),
                ),
                ("queued_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SYNCED", "Synced"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "offline_sync_queue",
                "indexes": [
                    models.Index(
                        fields=["device_id", "status"],
                        name="offline_syn_device__d22e4e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BirthRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending RO Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "birth_certificate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_of_birth",
                        to="hospital.birthcertificate",
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="births_as_father",
                        to="citizens.citizen",
                        to_field="din",
                    ),
                ),
                (
                    "health_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birth_submissions_as_worker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="births_as_mother",
                        to="citizens.citizen",
                        to_field="din",
                    ),
                ),
                (
                    "registrar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="birth_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice_of_birth",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_of_birth",
                        to="hospital.noticeofbirth",
                    ),
                ),
                (
                    "record_of_birth",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_of_birth",
                        to="hospital.recordofbirth",
                    ),
                ),
            ],
            options={
                "db_table": "birth_record_submissions",
                "indexes": [
                    models.Index(
                        fields=["status"], name="birth_recor_status_29eb42_idx"
                    ),
                    models.Index(
                        fields=["submitted_at"], name="birth_recor_submitt_09a7c2_idx"
                    ),
                ],
            },
        ),
    ]
