# Generated by Django 6.0.4 on 2026-04-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_ops', '0001_initial'),
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('event_type', models.CharField(choices=[('BIRTH', 'Birth'), ('DEATH', 'Death')], max_length=10)),
                ('queued_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offline_sync_queue',
                'indexes': [models.Index(fields=['device_id', 'status'], name='offline_syn_device__d22e4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BirthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_din', models.CharField(blank=True, max_length=12, null=True)),
                ('mother_din', models.CharField(max_length=12)),
                ('facility', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('child_full_name', models.CharField(max_length=255)),
                ('child_dob', models.DateField()),
                ('child_sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('born_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending RO Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_records_filed', to='admin_ops.systemuser')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='births_as_mother', to='citizens.citizen', to_field='din')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_records_reviewed', to='admin_ops.systemuser')),
            ],
            options={
                'db_table': 'birth_records',
                'indexes': [models.Index(fields=['status'], name='birth_recor_status_210370_idx'), models.Index(fields=['mother_din'], name='birth_recor_mother__0f1067_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_din', models.CharField(max_length=12)),
                ('facility', models.CharField(max_length=255)),
                ('cause_icd11', models.CharField(max_length=20)),
                ('cause_description', models.CharField(blank=True, max_length=255)),
                ('died_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending RO Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deceased', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_record', to='citizens.citizen', to_field='din')),
                ('health_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_records_filed', to='admin_ops.systemuser')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_records_reviewed', to='admin_ops.systemuser')),
            ],
            options={
                'db_table': 'death_records',
                'indexes': [models.Index(fields=['status'], name='death_recor_status_f82281_idx'), models.Index(fields=['deceased_din'], name='death_recor_decease_94fb48_idx')],
            },
        ),
    ]
