# Generated by Django 6.0.4 on 2026-04-25 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0003_alter_systemuser_password_hash_and_more'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthrecord',
            name='health_worker',
        ),
        migrations.RemoveField(
            model_name='birthrecord',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='birthrecord',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='birthrecord',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='deathrecord',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='deathrecord',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='deathrecord',
            name='reviewed_by',
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='child_din',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='child_sex',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='birthrecord',
            name='mother_din',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='deceased_din',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='BirthRecordSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending RO Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('health_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_submissions_as_worker', to='admin_ops.systemuser')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_request', to='hospital.birthrecord')),
                ('ro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_submissions_as_ro', to='admin_ops.systemuser')),
            ],
            options={
                'db_table': 'birth_record_submissions',
                'indexes': [models.Index(fields=['status'], name='birth_recor_status_29eb42_idx'), models.Index(fields=['submitted_at'], name='birth_recor_submitt_09a7c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeathRecordSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending RO Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('health_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_submissions_as_worker', to='admin_ops.systemuser')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_request', to='hospital.deathrecord')),
                ('ro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_submissions_as_ro', to='admin_ops.systemuser')),
            ],
            options={
                'db_table': 'death_record_submissions',
                'indexes': [models.Index(fields=['status'], name='death_recor_status_88fd5e_idx'), models.Index(fields=['submitted_at'], name='death_recor_submitt_389e2b_idx')],
            },
        ),
    ]
