# Generated by Django 6.0.4 on 2026-04-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizens", "0003_district_healthworker_province_registrar_and_more"),
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="birthrecord",
            old_name="child_din",
            new_name="birth_certificate_number",
        ),
        migrations.RemoveField(
            model_name="birthrecord",
            name="child_full_name",
        ),
        migrations.RemoveField(
            model_name="birthrecord",
            name="location",
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="child_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="child_other_names",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="child_surname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="date_of_registration",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="father_of_new_born",
                to="citizens.citizen",
                to_field="din",
            ),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="father_nationality",
            field=models.CharField(default="ZAMBIAN", max_length=255),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="father_occupation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="father_ssn",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="informant_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="informant_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="mother_nationality",
            field=models.CharField(default="ZAMBIAN", max_length=255),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="mother_ssn",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="birthrecord",
            name="postal_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deathrecord",
            name="certificate_verification_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="birthrecord",
            name="born_at",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name="birthrecord",
            name="child_dob",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="birthrecord",
            name="created_at",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name="birthrecord",
            name="facility",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="birthrecord",
            name="mother_din",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="deathrecord",
            name="certificate_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
