# Generated by Django 6.0.4 on 2026-04-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_din', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('method', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING_CONFIRMATION', 'Pending Citizen Confirmation'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=30)),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('biometric_challenge', models.CharField(blank=True, max_length=64, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CITIZEN', 'Citizen'), ('RO', 'Registration Officer'), ('REGISTRAR', 'Registrar'), ('SUPERVISOR', 'Supervisor'), ('HEALTH_WORKER', 'Health Worker'), ('THIRD_PARTY', 'Third Party')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('citizen_din', models.CharField(blank=True, max_length=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_users',
                'indexes': [models.Index(fields=['email'], name='system_user_email_57ef97_idx'), models.Index(fields=['role'], name='system_user_role_ca227b_idx'), models.Index(fields=['citizen_din'], name='system_user_citizen_57fb94_idx')],
            },
        ),
    ]
