# Generated by Django 6.0.4 on 2026-04-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_ops", "0001_initial"),
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thirdpartyenrollmentrequest",
            name="third_party_institution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_request",
                to="kyc.thirdpartyinstitution",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="kyc.thirdpartyinstitution",
            ),
        ),
        migrations.AddIndex(
            model_name="systemuser",
            index=models.Index(fields=["email"], name="system_user_email_57ef97_idx"),
        ),
        migrations.AddIndex(
            model_name="systemuser",
            index=models.Index(fields=["role"], name="system_user_role_ca227b_idx"),
        ),
        migrations.AddIndex(
            model_name="systemuser",
            index=models.Index(
                fields=["institution_din"], name="system_user_institu_f30a61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thirdpartyenrollmentrequest",
            index=models.Index(fields=["status"], name="third_party_status_078db3_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyenrollmentrequest",
            index=models.Index(
                fields=["submitted_at"], name="third_party_submitt_17ba1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["citizen_din", "status"], name="transaction_citizen_8a1f4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["reference"], name="transaction_referen_c33c6b_idx"
            ),
        ),
    ]
