# Generated by Django 6.0.4 on 2026-04-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_ops', '0001_initial'),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='kyc.thirdpartyinstitution'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['citizen_din', 'status'], name='transaction_citizen_8a1f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='transaction_referen_c33c6b_idx'),
        ),
    ]
