# Generated by Django 6.0.4 on 2026-04-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='password_hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='citizen_din',
            field=models.CharField(max_length=20),
        ),
    ]
