# Generated by Django 6.0.4 on 2026-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
