# Generated by Django 6.0.4 on 2026-04-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemuser",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="systemuser",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("CITIZEN", "Citizen"),
                    ("RO", "Registration Officer"),
                    ("REGISTRAR", "Registrar"),
                    ("SUPERVISOR", "Supervisor"),
                    ("HEALTH_WORKER", "Health Worker"),
                    ("THIRD_PARTY", "Third Party"),
                ],
                default="CITIZEN",
                max_length=100,
            ),
        ),
    ]
