# Generated by Django 6.0.4 on 2026-04-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0003_systemuser_is_email_verified_systemuser_otp_code_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="systemuser",
            name="system_user_citizen_57fb94_idx",
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("CITIZEN", "Citizen"),
                    ("REGISTRATION_OFFICER", "Registration Officer"),
                    ("REGISTRAR", "Registrar"),
                    ("SUPERVISOR", "Supervisor"),
                    ("HEALTH_WORKER", "Health Worker"),
                    ("THIRD_PARTY", "Third Party"),
                ],
                default="CITIZEN",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="systemuser",
            index=models.Index(
                fields=["institution_din"], name="system_user_institu_f30a61_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="systemuser",
            name="citizen_din",
        ),
    ]
