# Generated by Django 6.0.4 on 2026-04-25 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("citizens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citizen_din", models.CharField(max_length=12)),
                ("fields_requested", models.JSONField()),
                ("fields_granted", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Awaiting Citizen Response"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_requests",
                        to="citizens.citizen",
                        to_field="din",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_requests",
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("DENIED", "Denied")],
                        max_length=10,
                    ),
                ),
                ("fields_shared", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="citizens.citizen",
                    ),
                ),
                (
                    "kyc_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_record",
                        to="kyc.kycrequest",
                    ),
                ),
            ],
            options={
                "db_table": "consent_records",
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                (
                    "institution_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("reg_number", models.CharField(max_length=100, unique=True)),
                (
                    "oidc_client_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "oidc_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("permitted_scope", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrolled_institutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "third_party_institutions",
            },
        ),
        migrations.AddField(
            model_name="kycrequest",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kyc_requests",
                to="kyc.thirdpartyinstitution",
            ),
        ),
        migrations.AddIndex(
            model_name="thirdpartyinstitution",
            index=models.Index(fields=["status"], name="third_party_status_12f730_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyinstitution",
            index=models.Index(
                fields=["reg_number"], name="third_party_reg_num_4ff547_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycrequest",
            index=models.Index(
                fields=["citizen_din", "status"], name="kyc_request_citizen_ad40e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kycrequest",
            index=models.Index(
                fields=["institution", "status"], name="kyc_request_institu_bb0d81_idx"
            ),
        ),
    ]
