# Generated by Django 6.0.4 on 2026-04-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyinstitution',
            name='permitted_scope',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
