# Generated by Django 6.0.4 on 2026-05-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyinstitution',
            name='institution_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartyinstitution',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartyinstitution',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
