# Generated by Django 6.0.4 on 2026-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_thirdpartyinstitution_permitted_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyinstitution',
            name='institution_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
