# Generated by Django 6.0.4 on 2026-05-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
        ('kyc', '0002_thirdpartyinstitution_institution_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='citizens.citizen', to_field='din')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_citizens', to='kyc.thirdpartyinstitution')),
            ],
            options={
                'db_table': 'partner_links',
                'indexes': [models.Index(fields=['citizen', 'institution'], name='partner_lin_citizen_7d7849_idx')],
                'unique_together': {('citizen', 'institution')},
            },
        ),
    ]
