from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime
from enum import Enum
from typing import Optional


# -------------------------------------------------------------------
# Enums
# -------------------------------------------------------------------
class EnrollmentStatus(str, Enum):
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'


# -------------------------------------------------------------------
# Enrollment Request Schemas
# -------------------------------------------------------------------
class EnrollmentRequestCreate(BaseModel):
    """
    POST /enrollments/ (Internal Use)
    Triggered when a citizen submits their initial enrollment payload.
    """
    citizen_id: int = Field(..., description="Internal Django PK of the pending Citizen")


class EnrollmentApproval(BaseModel):
    """
    PATCH /enrollments/{id}/approve
    Payload submitted by RO or system to approve the enrollment.
    """
    activation_challenge: str = Field(
        ..., 
        max_length=64, 
        description="Random nonce generated by server for the citizen device to sign"
    )
    activation_challenge_expires_at: datetime = Field(
        ..., 
        description="Timestamp when the challenge expires"
    )


class EnrollmentRejection(BaseModel):
    """
    PATCH /enrollments/{id}/reject
    Payload submitted by RO to reject the enrollment.
    """
    rejection_reason: str = Field(
        ...,  
        min_length=10, 
        description="Detailed reason for rejection (e.g., 'Biometric duplicate detected', 'Invalid NRC')"
    )


class EnrollmentRequestResponse(BaseModel):
    """
    GET /enrollments/{id}
    Standard response showing the status of an enrollment request.
    """
    model_config = ConfigDict(from_attributes=True)

    id: int
    citizen_id: int
    submitted_at: datetime
    ro_id: Optional[int] = Field(None, description="ID of the Registration Officer who reviewed this")
    reviewed_at: Optional[datetime] = None
    status: EnrollmentStatus
    rejection_reason: Optional[str] = None
    activation_challenge: Optional[str] = None
    activation_challenge_expires_at: Optional[datetime] = None


class EnrollmentRequestFilterParams(BaseModel):
    """
    Query parameters for GET /enrollments/
    Useful for RO Dashboard to filter pending requests.
    """
    status: Optional[EnrollmentStatus] = Field(default=EnrollmentStatus.PENDING)
    ro_id: Optional[int] = Field(None, description="Filter by specific Registration Officer")
    submitted_after: Optional[datetime] = None
    submitted_before: Optional[datetime] = None
    page: int = Field(default=1, ge=1)
    page_size: int = Field(default=20, ge=1, le=100)


# -------------------------------------------------------------------
# Registration Officer Schemas
# -------------------------------------------------------------------
class RegistrationOfficerBase(BaseModel):
    district: str = Field(..., max_length=100, description="District the RO is assigned to")


class RegistrationOfficerCreate(RegistrationOfficerBase):
    """
    POST /officers/
    Used by an Admin to promote a SystemUser to a Registration Officer.
    """
    user_id: int = Field(..., description="ID of the SystemUser being assigned the RO role")
    enrolled_by_id: Optional[int] = Field(None, description="ID of the Admin assigning this role")


class RegistrationOfficerUpdate(BaseModel):
    """
    PATCH /officers/{id}
    Used to transfer an RO to a new district.
    """
    district: Optional[str] = Field(None, max_length=100)


class RegistrationOfficerResponse(RegistrationOfficerBase):
    """
    GET /officers/{id}
    Profile response for an RO.
    """
    model_config = ConfigDict(from_attributes=True)

    id: int
    user_id: int
    enrolled_by_id: Optional[int] = None
    created_at: datetime


class PaginatedEnrollmentList(BaseModel):
    """
    GET /enrollments/
    RO Dashboard list representation.
    """
    total: int
    page: int
    page_size: int
    items: list[EnrollmentRequestResponse]