# Generated by Django 6.0.4 on 2026-04-29 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "district",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "provinces",
                "db_table": "province",
            },
        ),
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "din",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("nrc", models.CharField(max_length=15, null=True, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("residential_address", models.CharField(max_length=255, null=True)),
                ("maiden_name", models.CharField(max_length=255, null=True)),
                ("dob", models.DateField()),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "nrc_front_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "nrc_back_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "face_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("public_key", models.TextField(null=True)),
                (
                    "activation_nonce",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("ACTIVE", "active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "suspended"),
                            ("DECEASED", "deceased"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("bem", "Bemba"),
                            ("nya", "Nyanja"),
                            ("toi", "Tonga"),
                            ("loz", "Lozi"),
                        ],
                        default="en",
                        max_length=20,
                    ),
                ),
                ("challenge_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "citizen_type",
                    models.CharField(
                        choices=[
                            ("CHILD_ABOVE_16", "Child above 16"),
                            ("CHILD_UNDER_16", "Child under 16"),
                            ("ADULT", "Adult"),
                            ("SENIOR", "Senior"),
                        ],
                        default="ADULT",
                        max_length=20,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "Never Been to School"),
                            ("PRIMARY", "Primary"),
                            ("SECONDARY", "Secondary"),
                            ("TERTIARY", "Tertiary"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("social_id", models.CharField(blank=True, max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citizens",
                        to="citizens.district",
                    ),
                ),
            ],
            options={
                "db_table": "citizen",
            },
        ),
        migrations.CreateModel(
            name="BiometricRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        blank=True,
                        help_text="512-float InsightFace embedding.",
                        null=True,
                    ),
                ),
                (
                    "embedding_quantized",
                    models.BinaryField(
                        blank=True,
                        help_text="64-bytes quantized embedding. Stable across caputers. Input to DIN derivation.",
                        null=True,
                    ),
                ),
                (
                    "din_commitment",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256(quantized_embedding + salt). Used to very face-to-DIN binding.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "face_image_path",
                    models.CharField(
                        blank=True,
                        help_text="secure storage path to the original face photo",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("facial_template", models.TextField(blank=True, null=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "citizen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_record",
                        to="citizens.citizen",
                    ),
                ),
            ],
            options={
                "db_table": "biometric_record",
            },
        ),
        migrations.CreateModel(
            name="FamilyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("PARENT", "Parent"),
                            ("CHILD", "Child"),
                            ("SIBLING", "Sibling"),
                            ("SPOUSE", "Spouse"),
                            ("GUARDIAN", "Guardian"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_link_from",
                        to="citizens.citizen",
                    ),
                ),
                (
                    "related_citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_link_to",
                        to="citizens.citizen",
                    ),
                ),
            ],
            options={
                "db_table": "family_link",
            },
        ),
        migrations.CreateModel(
            name="HealthWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                (
                    "facility_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_worker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "health_worker",
            },
        ),
        migrations.AddField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="citizens.province",
            ),
        ),
        migrations.CreateModel(
            name="Registrar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrars",
                        to="citizens.district",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrar_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "registrar",
            },
        ),
        migrations.CreateModel(
            name="RegistrationOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                (
                    "station_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_officers",
                        to="citizens.district",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_officer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "registration_officer",
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervisors",
                        to="citizens.district",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "supervisor",
            },
        ),
        migrations.AddIndex(
            model_name="citizen",
            index=models.Index(fields=["din"], name="citizen_din_18c8d8_idx"),
        ),
        migrations.AddIndex(
            model_name="citizen",
            index=models.Index(fields=["nrc"], name="citizen_nrc_6df8ab_idx"),
        ),
        migrations.AddIndex(
            model_name="citizen",
            index=models.Index(fields=["status"], name="citizen_status_f8724e_idx"),
        ),
        migrations.AddIndex(
            model_name="citizen",
            index=models.Index(fields=["gender"], name="citizen_gender_d542b6_idx"),
        ),
        migrations.AddIndex(
            model_name="citizen",
            index=models.Index(fields=["district"], name="citizen_distric_13c287_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="familylink",
            unique_together={("citizen", "related_citizen", "relationship_type")},
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("name", "province")},
        ),
    ]
