# Generated by Django 6.0.4 on 2026-04-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('nrc', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('public_key', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('SUSPENDED', 'suspended'), ('DECEASED', 'deceased')], default='PENDING', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('bem', 'Bemba'), ('nya', 'Nyanja'), ('toi', 'Tonga'), ('loz', 'Lozi')], default='en', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'citizen',
                'indexes': [models.Index(fields=['din'], name='citizen_din_18c8d8_idx'), models.Index(fields=['nrc'], name='citizen_nrc_6df8ab_idx'), models.Index(fields=['status'], name='citizen_status_f8724e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BiometricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(blank=True, help_text='512-float InsightFace embedding.', null=True)),
                ('embedding_quantized', models.BinaryField(blank=True, help_text='64-bytes quantized embedding. Stable across caputers. Input to DIN derivation.', null=True)),
                ('din_commitment', models.CharField(blank=True, help_text='SHA-256(quantized_embedding + salt). Used to very face-to-DIN binding.', max_length=64, null=True)),
                ('face_image_path', models.CharField(blank=True, help_text='secure storage path to the original face photo', max_length=500, null=True)),
                ('facial_template', models.TextField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Citizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_record', to='citizens.citizen')),
            ],
            options={
                'db_table': 'biometric_record',
            },
        ),
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('SPOUSE', 'Spouse'), ('GUARDIAN', 'Guardian')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_link_from', to='citizens.citizen')),
                ('related_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_link_to', to='citizens.citizen')),
            ],
            options={
                'db_table': 'family_link',
                'unique_together': {('citizen', 'related_citizen', 'relationship_type')},
            },
        ),
    ]
