# Generated by Django 6.0.4 on 2026-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='education_level',
            field=models.CharField(blank=True, choices=[('NONE', 'Never Been to School'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='maiden_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='social_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
