# Generated by Django 6.0.4 on 2026-04-27 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizens", "0002_remove_citizen_email_remove_citizen_password_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "district",
            },
        ),
        migrations.CreateModel(
            name="HealthWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                (
                    "facility_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "health_worker",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "provinces",
                "db_table": "province",
            },
        ),
        migrations.CreateModel(
            name="Registrar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "registrar",
            },
        ),
        migrations.CreateModel(
            name="RegistrationOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                (
                    "station_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "registration_officer",
            },
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "supervisor",
            },
        ),
        migrations.RemoveIndex(
            model_name="citizen",
            name="citizen_provinc_f26316_idx",
        ),
        migrations.RenameField(
            model_name="biometricrecord",
            old_name="Citizen",
            new_name="citizen",
        ),
        migrations.AddField(
            model_name="citizen",
            name="citizen_type",
            field=models.CharField(
                choices=[
                    ("CHILD_ABOVE_16", "Child above 16"),
                    ("CHILD_UNDER_16", "Child under 16"),
                    ("ADULT", "Adult"),
                    ("SENIOR", "Senior"),
                ],
                default="ADULT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="citizen",
            name="residential_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="citizen",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="citizens",
                to="citizens.district",
            ),
        ),
        migrations.AddIndex(
            model_name="citizen",
            index=models.Index(fields=["district"], name="citizen_distric_13c287_idx"),
        ),
        migrations.AddField(
            model_name="healthworker",
            name="citizen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_worker_profile",
                to="citizens.citizen",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="citizens.province",
            ),
        ),
        migrations.AddField(
            model_name="registrar",
            name="citizen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrar_profile",
                to="citizens.citizen",
            ),
        ),
        migrations.AddField(
            model_name="registrar",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrars",
                to="citizens.district",
            ),
        ),
        migrations.AddField(
            model_name="registrationofficer",
            name="citizen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_officer_profile",
                to="citizens.citizen",
            ),
        ),
        migrations.AddField(
            model_name="registrationofficer",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registration_officers",
                to="citizens.district",
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="citizen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supervisor_profile",
                to="citizens.citizen",
            ),
        ),
        migrations.AddField(
            model_name="supervisor",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervisors",
                to="citizens.district",
            ),
        ),
        migrations.RemoveField(
            model_name="citizen",
            name="province",
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("name", "province")},
        ),
    ]
