# Generated by Django 6.0.4 on 2026-04-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_citizen_gender_province'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='citizen',
            new_name='citizen_gender_d542b6_idx',
            old_name='citizen_gender_idx',
        ),
        migrations.RenameIndex(
            model_name='citizen',
            new_name='citizen_provinc_f26316_idx',
            old_name='citizen_province_idx',
        ),
    ]
