# Generated by Django 6.0.4 on 2026-04-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_rename_citizen_gender_idx_citizen_gender_d542b6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='din',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='nrc',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='public_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'suspended'), ('DECEASED', 'deceased'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
