# Generated by Django 6.0.4 on 2026-04-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0004_alter_citizen_din_alter_citizen_nrc_and_more'),
        ('citizens', '0004_citizen_activation_nonce_and_more'),
    ]

    operations = [
    ]
