# Generated by Django 6.0.4 on 2026-04-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din', models.CharField(db_index=True, max_length=12)),
                ('event_type', models.CharField(choices=[('generated', 'Generated'), ('verified', 'Verified'), ('expired', 'Expired'), ('invalid', 'Invalid Signature')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['din', '-timestamp'], name='qr_qrlog_din_05674d_idx')],
            },
        ),
    ]
