# Generated by Django 6.0.4 on 2026-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_id", models.CharField(max_length=50)),
                ("actor_role", models.CharField(max_length=30)),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=50)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")],
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metastamp", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "log_signature",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["actor_id"], name="audit_logs_actor_i_0badd2_idx"
                    ),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_logs_target__9fc8de_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
                    ),
                ],
            },
        ),
    ]
